baseURL = "https://swaptr.github.io/site/"
languageCode = "en-us"
title = "swaptr's blog"
theme = "/"
paginate = 5
publishDir = "docs"

copyright = "© The MIT License (MIT)"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
subtitle = "This was supposed to be fun and it's not fun because it's too hard."

# Optional 64x64 avatar image.
avatar = "https://avatars.githubusercontent.com/u/83858160?v=4"

# Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
favicon = "icons/favicon.ico"

featherIconsCDN = true

mode = "auto" # "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/swaptr"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/swaptr06"

[[params.social]]
name = "RSS"
icon = "rss"
url = "index.xml"

[taxonomies]
tag = "tags"
